version: "3.9"

services:
  app:
    build:
      context: .
      args:
        DEV: "true"
    ports:
      - "8000:8000"
      - "5678:5678"

    volumes:
      - ./app:/app
    command: sh -c "python manage.py wait_for_db &&
                    python manage.py migrate &&  
                    python manage.py runserver 0.0.0.0:8000"
    environment:
      DB_HOST: db
      DB_NAME: devdb
      DB_USER: admin
      DB_PASS: pass
    depends_on:
      - db

    deploy:
      resources:
        limits:
          cpus: "0.5"      # max about 50% of one core
          memory: "2G"   # max ~512MB RAM
        reservations:
          cpus: "0.25"     # soft minimum CPU
          memory: "1G"   # soft minimum RAM

  db:
    image: postgres:13-alpine
    volumes:
      - dev-data-database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass

volumes:
  dev-data-database:
  dev-static-data:
