---
name: AutoCheck

on: [push]


jobs: 
  test-lint:
    name: Test and lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login in Docker
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUP_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: CheckOut
        uses: actions/checkout@v6
        
      - name: Run Test
        run: docker compose run --rm app sh -c "python manage.py test"

      - name: lint Check
        run: docker compose run --rm app sh -c "flake8"
        
